name: Build and Release APK

on:
  push:
    tags:
      - 'v*.*.*'  # Triggers on version tags like v1.0.0

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'
        
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.24.5'
        channel: 'stable'
        cache: true
        
    - name: Get dependencies
      run: flutter pub get
      
    - name: Build APK
      run: flutter build apk --target-platform android-arm64 --split-per-abi --release
      
    - name: Get version from tag
      id: version
      run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
      
    - name: Rename APK with version
      run: |
        mkdir -p release
        cp build/app/outputs/flutter-apk/app-arm64-v8a-release.apk release/veelog-${{ steps.version.outputs.VERSION }}-arm64-v8a.apk
        
    - name: Create GitHub Release
      uses: actions/create-release@v1
      id: create_release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: VeeLog ${{ steps.version.outputs.VERSION }}
        draft: false
        prerelease: false
        body: |
          ## VeeLog ${{ steps.version.outputs.VERSION }}
          
          ### Download
          - **Android (ARM64)**: veelog-${{ steps.version.outputs.VERSION }}-arm64-v8a.apk
          
          ### Installation
          1. Download the APK file
          2. Enable "Install unknown apps" in Android settings
          3. Install the APK
          
          ### Zapstore
          This release is also available on [Zapstore](https://zapstore.dev)
          
    - name: Upload APK to Release
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: release/veelog-${{ steps.version.outputs.VERSION }}-arm64-v8a.apk
        asset_name: veelog-${{ steps.version.outputs.VERSION }}-arm64-v8a.apk
        asset_content_type: application/vnd.android.package-archive
        
    - name: Generate APK checksums
      run: |
        cd release
        sha256sum veelog-${{ steps.version.outputs.VERSION }}-arm64-v8a.apk > veelog-${{ steps.version.outputs.VERSION }}-arm64-v8a.apk.sha256
        
    - name: Upload checksums to Release
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: release/veelog-${{ steps.version.outputs.VERSION }}-arm64-v8a.apk.sha256
        asset_name: veelog-${{ steps.version.outputs.VERSION }}-arm64-v8a.apk.sha256
        asset_content_type: text/plain